language: go

install:
  - go get github.com/mitchellh/gox

script: 
	- go test -bench=. ./...
	- gox -os="linux darwin freebsd" -arch="386 amd64 arm" -output="bin/myq_status.{{.OS}}-{{.Arch}}"
	- tar cvzf myq_tools.tgz bin/*

git:
    submodules: false

notifications:
  email: jay.janssen@percona.com
  on_success: change
  on_failure: change
