language: go
go: tip
env:
  # "gvm update" resets GOOS and GOARCH environment variable, workaround it by setting
  # BUILD_GOOS and BUILD_GOARCH and overriding GOARCH and GOOS in the build script
  global:
    - BUILD_GOARCH=amd64
    - BUILD_GOARCH=386
    - BUILD_GOARCH=arm
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin
    - BUILD_GOOS=windows
script:
  - gvm cross $BUILD_GOOS $BUILD_GOARCH
  - GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS go build

  # only test on linux
  - if [ $BUILD_GOOS == "linux" ]; then GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS go test -bench=. ./...; fi
git:
  submodules: false
notifications:
  email:
    recipients:
    - jay.janssen@gmail.com
    on_success: change
    on_failure: change
deploy:
  provider: releases
  api_key:
    secure: Zpb1YS6oYPf+KJPWp/ye8bW+pULxmZkhoBBkFIgyM30FbiCmPuZJLqm7Kkw4gUAYisj90lrsGedpvK4aHlE4BZXYt5yBuXHapjImACzX2rm1ssPbtAoyx/68SARSTB3Bm2/MCfI8Py5IRlJCzyTmK1quopWYyUGd/uSbmbsmJzQ=
  file: "myq_tools.tgz"
  skip_cleanup: true 
  on:
    repo: jayjanssen/myq-tools
    all_branches: true
    tags: true