language: go

install:
  - go get github.com/mitchellh/gox

script: ./build.sh

git:
    submodules: false

notifications:
  email:
    recipients:
      - jay.janssen@gmail.com
    on_success: change
    on_failure: change
